# Generated by Django 5.0.2 on 2024-02-28 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0002_parent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parent',
            new_name='Parents',
        ),
    ]
